#!/bin/sh


######################################################
# This script spawns parallel processes to read the 
# configuration files generated by "run-config.sh" 
# line by line and execute them while logging to 
# appropriate log files 
######################################################

##################GLOBALS#################
DOMAIN="local"
TESTSUBDOMAIN="test"
ENV="test"   # Leave it blank for production
CONFIGPREFIX="vlabs-cmds.conf"
LOGPREFIX="./logs/"
PARALLEL="2"
LOGLEVEL="1"
FORCERUN="1"
##########################################

# Error message if the script is not run with root privileges"
if [ "$USER" != "root" ] ; then
  echo " This script should be run with root privileges...Exiting"
  exit
fi

# Spawn parallel processes
execute_cmds()
 {
  IFS=$'\n'
  errflag=0
  for cmd in $(cat $1);
  do
  # echo $cmd
   if [ "`echo $cmd | grep '^#'`" == "$cmd" ] ; then
    #This is a comment, parse arguments to get the hostname
    COMMENT=$(echo $cmd | sed 's/#//g')
    if [ "`echo $COMMENT | grep '\-start'`" == "$COMMENT" ] ; then
     errflag=0
     LOGFILE=$LOGPREFIX/$(echo $COMMENT | sed 's/-start//g')
      if [ -f "$LOGFILE.log" ] ; then
        rm -rf $LOGFILE.log
      fi
    fi
   else
    #This is a command, just execute it if there are no previous errors and send output to the logfile
    if [ "$errflag" == 0 ] ; then
       if [ "$LOGLEVEL" = "1" ] ; then
          #Verbose logging
          echo "VDEBUG: Executing [[ $cmd ]] " >> $LOGFILE.log
       fi
        eval $cmd >> $LOGFILE.log 2>&1
       EXITSTATUS=$?
       if [ "$EXITSTATUS" != 0 ] ; then
         echo "VERROR: Error occured. Unable to continue" >> $LOGFILE.log
	 # If forcerun flag is set, dont change the error flag
         if [ "$FORCERUN" == "0" ] ; then
          errflag=1
         fi # End of force run check
       fi # End of command exit status check
    fi  # End of error flag check
   fi # End of previous error check
  done
 }

# Main Control
i=0
while [ "$i" \< "$PARALLEL" ];  
do 
#  cat ./$CONFIGPREFIX.$i | while read cmd ; 
  execute_cmds ./$CONFIGPREFIX.$i & 
  i=`expr $i + 1`
done

wait
# Generate new Apache config
./gen-apache-config.sh

# Generate new labs-info
./gen-lab-info.sh
